db:
  image: postgres
redis:
  image: redis
  ports:
    - "6379:6379"
web:
  build: .
  environment:
    T17_SECRET_KEY:
    T17_MANDRILL_API_KEY:
    T17_PHONE_NUMBER:
    T17_DB_NAME:
    T17_DB_USER:
    T17_DB_PASSWORD:
  command: /opt/django/run.sh
  volumes:
    - /opt/django/textress
  ports:
    - "8000:8000"
  links:
    - db
    - redis